---
title: "GovHack2019"
author: "Sean, Vic, Tylor, Roger, Pegah"
output: html_document
---

```{r setup, include=FALSE}
# define paths for working direcotires (http://www.randigriffin.com/2017/04/25/how-to-knit-for-mysite.html)
knitr::opts_knit$set(base.dir = "C:/Users/Buntoss/Documents/GitHub/GovHack2019",
                     base.url = "/")
knitr::opts_chunk$set(fig.path = "plots/",
  echo = FALSE, message = FALSE, warning = FALSE)
source('Attributes_Insolvent_Debtors_analysis.R')
```

## Analysis of Insolvency Reports by State

```{r fig.height=3}
Analysis$Plots$Attributes_Insolvency_by_State

```

```{r fig.height=5}
Analysis$Plots$Attributes_Insolvency_by_State_n_Assets

```

```{r fig.height=5}
Analysis$Plots$Attributes_Insolvency_by_State_n_Debts

```

```{r fig.height=3}
Analysis$Plots$Attributes_Insolvency_by_State_n_Gender

```

```{r fig.height=3}
Analysis$Plots$Attributes_Insolvency_by_State_n_Situation

```

## Analysis of Insolvency Reports by SA3

```{r fig.height=3}
Analysis$Plots$Attributes_Insolvency_by_SA3

```

```{r fig.height=3}
Analysis$Plots$Attributes_Insolvency_by_SA3_n_State

```

## Analysis of Insolvency Reports by Over Time

```{r fig.height=3}
Analysis$Plots$Attributes_Insolvency_by_Year_n_State

```

## Analysis of Insolvency Reports by Jobs

```{r fig.height=5}
Analysis$Plots$Attributes_Insolvency_by_Job_n_State

```
